version: '3.8'

services:
  sensor-simulator:
    image: python:3.9-alpine
    container_name: plant_a_sensor_simulator
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./../scripts:/app
      - ./../data:/data
    command: >
      sh -c "
        apk add --no-cache curl &&
        pip install requests influxdb-client &&
        python sensor_simulator.py --plant-id A --plant-name 'Plant A' --location 'North District'
      "
    environment:
      - INFLUXDB_URL=http://vm1:8086
      - INFLUXDB_TOKEN=water_monitoring_token_2024
      - INFLUXDB_ORG=water_treatment
      - INFLUXDB_BUCKET=water_metrics
      - PLANT_ID=A
      - PLANT_NAME=Plant A
    networks:
      - plant_network

  data-collector:
    image: python:3.9-alpine
    container_name: plant_a_data_collector
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./../scripts:/app
      - ./../data:/data
    command: >
      sh -c "
        apk add --no-cache curl &&
        pip install requests influxdb-client psutil &&
        python data_collector.py --plant-id A
      "
    environment:
      - INFLUXDB_URL=http://vm1:8086
      - INFLUXDB_TOKEN=water_monitoring_token_2024
      - INFLUXDB_ORG=water_treatment
      - INFLUXDB_BUCKET=water_metrics
      - PLANT_ID=A
      - COLLECTION_INTERVAL=30
    networks:
      - plant_network

  local-monitor:
    image: nginx:alpine
    container_name: plant_a_local_monitor
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./../configs/local-nginx.conf:/etc/nginx/nginx.conf
      - ./../data/logs:/var/log/nginx
    networks:
      - plant_network

  health-checker:
    image: alpine:latest
    container_name: plant_a_health_checker
    restart: unless-stopped
    volumes:
      - ./../scripts:/scripts
    command: >
      sh -c "
        apk add --no-cache curl &&
        chmod +x /scripts/health_check.sh &&
        while true; do
          /scripts/health_check.sh;
          sleep 60;
        done
      "
    networks:
      - plant_network

networks:
  plant_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
