version: '3.8'

services:
  influxdb:
    image: influxdb:2.7
    container_name: water_monitoring_influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=watermonitor2024
      - DOCKER_INFLUXDB_INIT_ORG=water_treatment
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=water_monitoring_token_2024
      - DOCKER_INFLUXDB_INIT_BUCKET=water_metrics
    volumes:
      - ./../data/influxdb:/var/lib/influxdb2
    networks:
      - water_monitoring_network

  nginx:
    image: nginx:alpine
    container_name: water_monitoring_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./../configs/nginx.conf:/etc/nginx/nginx.conf
      - ./../ssl:/etc/nginx/ssl
      - ./../data/nginx/logs:/var/log/nginx
    depends_on:
      - influxdb
    networks:
      - water_monitoring_network

  grafana:
    image: grafana/grafana:latest
    container_name: water_monitoring_grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=watermonitor2024
    volumes:
      - ./../data/grafana:/var/lib/grafana
    networks:
      - water_monitoring_network

networks:
  water_monitoring_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
